function tracks = initializeTracks(min_height)
% create an empty array of tracks
tracks = struct(...
    'id', {}, ...
    'bbox', {}, ...
    'stateKalmanFilter', {},...
    'age', {}, ...
    'totalVisibleCount', {}, ...
    'colorHist', {}, ...
    'consecutiveInvisibleCount', {}, ...
    'min_height', min_height);
end